target-version = "py311"
line-length = 100

[lint]
select = ["E", "W", "F", "I", "UP", "B", "SIM", "RUF"]
ignore = ["E501", "B008"]

[lint.isort]
known-first-party = ["models", "utils"]

[lint.per-file-ignores]
"models/archs/*" = ["B", "SIM", "RUF", "UP"]
